// apps/react/src/app/nav/nav.tsx
import { Link } from 'react-router-dom';
import './nav.scss';

export function Nav() {
  return (
    <nav className="navbar navbar-expand-lg navbar-light bg-light">
      <div className="container-fluid">
        <Link className="navbar-brand" to="/">
          Elf
        </Link>

        <button className="navbar-toggler" type="button">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse">
          <ul className="navbar-nav me-auto mb-2 mb-lg-0">
            <li className="nav-item">
              <Link className="nav-link" to="/">
                Home
              </Link>
            </li>

            <li className="nav-item">
              <Link className="nav-link" to="/todos">
                Todos
              </Link>
            </li>

            <li className="nav-item">
              <Link className="nav-link" to="/products">
                Products
              </Link>
            </li>

            <li className="nav-item">
              <Link className="nav-link" to="/login">
                Login
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
}

export default Nav;

// apps/ng/src/app/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'elf-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss']
})
export class NavComponent {
  navItems = ['Todos', 'Users', 'Contacts'];

}

<nav class="navbar navbar-expand-lg bg ps-3 pe-4 nav-purple-bg">
  <div class="container-fluid">
    <a routerLink="/">
      <img src="../../assets/elf.svg" class="logo">
    </a>
    <ul class="navbar-nav">
      <li *ngFor="let item of navItems" class="nav-item mx-2">
        <a routerLinkActive="text-dark" [routerLink]="item.toLowerCase()" class='nav-link text-light'>{{ item }}</a>
      </li>
    </ul>
  </div>
</nav>
